env_name: pickplace

pickplace_env:
  action_scale: 0.05
  max_steps: 300
  n_substeps: 10
  cube_low: [0.15, -0.15, 0.015]
  cube_high: [0.30, 0.15, 0.015]
  place_target: [0.18, 0.0, 0.015]
  ring_center: [0.18, 0.0]
  ring_exclusion_radius: 0.065
  passive_pose: [0.0, -1.0, 0.7, 0.9, 0.0, 0.0]

train:
  n_envs: 8
  net_arch: [256, 256, 256, 256]
  total_timesteps: 100000
  learning_rate: 3e-4
  batch_size: 256
  buffer_size: 100000
  learning_starts: 10000
  checkpoint_freq: 50000
  tau: 0.005
  gamma: 0.99
  eval_freq: 50000
  n_eval_episodes: 10

wandb:
  project: robot-arm
  entity: mvlasenko
  enabled: true
