defaults:
  - env: pickplace
  - _self_

algorithm: ppo
resume: null

train:
  n_envs: 16
  net_arch: [256, 256, 256, 256]
  input_batchnorm: true
  total_timesteps: 20_000_000
  learning_rate: 3e-4
  batch_size: 4096
  gamma: 0.95
  log_interval: 1
  checkpoint_freq: 1_000_000
  eval_freq: 1_000_000
  n_eval_episodes: 32

sac:
  buffer_size: 100_000
  learning_starts: 100_000
  train_freq: 1
  gradient_steps: 1
  tau: 0.005

ppo:
  n_steps: 2048
  n_epochs: 2
  clip_range: 0.2
  ent_coef: 0.001
  gae_lambda: 0.95
  vf_coef: 1.0

wandb:
  project: robot-arm
  entity: mvlasenko
  enabled: true
